### ISSUE TITLE
Move the date up in the JSON file

### ISSUE THREAD

**Issue by Gustry** [Mariosmsk/qgis-plugins-downloads#2]
Even if a plugin doesn't have any update, its `date` is updated in the JSON file.

It produces a big git diff : https://github.com/Mariosmsk/qgis-plugins-downloads/commit/cf7d66590a8cc46b71c8baa8eb2f4bc5389ae155

The date is the same for all plugins, so it would be better to move the date up in the JSON file, as a general properties for all plugins, no ?

So then the diff file would be way smaller, only for a plugin having a different number of downloads.

What do you think ?

**Comment by Mariosmsk** [comment]
Hi @Gustry, 

Yes, I agree, you are right. It's better to have only one-time the date in JSON file.

**Comment by Gustry** [comment]
Ok, it was just an idea, to be able to read a diff file easily in github with way fewer lines updated.

I won't work on that, as I guess you know the code better than me

**Comment by Mariosmsk** [comment]
Thanks @Gustry!
